// Generated by gencpp from file move_demo/GripperControlRequest.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_GRIPPERCONTROLREQUEST_H
#define MOVE_DEMO_MESSAGE_GRIPPERCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_demo
{
template <class ContainerAllocator>
struct GripperControlRequest_
{
  typedef GripperControlRequest_<ContainerAllocator> Type;

  GripperControlRequest_()
    : width(0.0)  {
    }
  GripperControlRequest_(const ContainerAllocator& _alloc)
    : width(0.0)  {
  (void)_alloc;
    }



   typedef float _width_type;
  _width_type width;





  typedef boost::shared_ptr< ::move_demo::GripperControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_demo::GripperControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GripperControlRequest_

typedef ::move_demo::GripperControlRequest_<std::allocator<void> > GripperControlRequest;

typedef boost::shared_ptr< ::move_demo::GripperControlRequest > GripperControlRequestPtr;
typedef boost::shared_ptr< ::move_demo::GripperControlRequest const> GripperControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_demo::GripperControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_demo::GripperControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_demo::GripperControlRequest_<ContainerAllocator1> & lhs, const ::move_demo::GripperControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_demo::GripperControlRequest_<ContainerAllocator1> & lhs, const ::move_demo::GripperControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_demo::GripperControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_demo::GripperControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::GripperControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::GripperControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::GripperControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::GripperControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_demo::GripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ceb3374c4c9de569f66ba7b628c0b46b";
  }

  static const char* value(const ::move_demo::GripperControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xceb3374c4c9de569ULL;
  static const uint64_t static_value2 = 0xf66ba7b628c0b46bULL;
};

template<class ContainerAllocator>
struct DataType< ::move_demo::GripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_demo/GripperControlRequest";
  }

  static const char* value(const ::move_demo::GripperControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_demo::GripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 width\n"
;
  }

  static const char* value(const ::move_demo::GripperControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_demo::GripperControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_demo::GripperControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_demo::GripperControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_GRIPPERCONTROLREQUEST_H
