// Generated by gencpp from file move_demo/GripperControl.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_GRIPPERCONTROL_H
#define MOVE_DEMO_MESSAGE_GRIPPERCONTROL_H

#include <ros/service_traits.h>


#include <move_demo/GripperControlRequest.h>
#include <move_demo/GripperControlResponse.h>


namespace move_demo
{

struct GripperControl
{

typedef GripperControlRequest Request;
typedef GripperControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperControl
} // namespace move_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_demo::GripperControl > {
  static const char* value()
  {
    return "be5ef003f22cb11bc267a44b935e1625";
  }

  static const char* value(const ::move_demo::GripperControl&) { return value(); }
};

template<>
struct DataType< ::move_demo::GripperControl > {
  static const char* value()
  {
    return "move_demo/GripperControl";
  }

  static const char* value(const ::move_demo::GripperControl&) { return value(); }
};


// service_traits::MD5Sum< ::move_demo::GripperControlRequest> should match
// service_traits::MD5Sum< ::move_demo::GripperControl >
template<>
struct MD5Sum< ::move_demo::GripperControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_demo::GripperControl >::value();
  }
  static const char* value(const ::move_demo::GripperControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_demo::GripperControlRequest> should match
// service_traits::DataType< ::move_demo::GripperControl >
template<>
struct DataType< ::move_demo::GripperControlRequest>
{
  static const char* value()
  {
    return DataType< ::move_demo::GripperControl >::value();
  }
  static const char* value(const ::move_demo::GripperControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_demo::GripperControlResponse> should match
// service_traits::MD5Sum< ::move_demo::GripperControl >
template<>
struct MD5Sum< ::move_demo::GripperControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_demo::GripperControl >::value();
  }
  static const char* value(const ::move_demo::GripperControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_demo::GripperControlResponse> should match
// service_traits::DataType< ::move_demo::GripperControl >
template<>
struct DataType< ::move_demo::GripperControlResponse>
{
  static const char* value()
  {
    return DataType< ::move_demo::GripperControl >::value();
  }
  static const char* value(const ::move_demo::GripperControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_GRIPPERCONTROL_H
