// Generated by gencpp from file move_demo/GripperControlResponse.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_GRIPPERCONTROLRESPONSE_H
#define MOVE_DEMO_MESSAGE_GRIPPERCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_demo
{
template <class ContainerAllocator>
struct GripperControlResponse_
{
  typedef GripperControlResponse_<ContainerAllocator> Type;

  GripperControlResponse_()
    : success(false)  {
    }
  GripperControlResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::move_demo::GripperControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_demo::GripperControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GripperControlResponse_

typedef ::move_demo::GripperControlResponse_<std::allocator<void> > GripperControlResponse;

typedef boost::shared_ptr< ::move_demo::GripperControlResponse > GripperControlResponsePtr;
typedef boost::shared_ptr< ::move_demo::GripperControlResponse const> GripperControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_demo::GripperControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_demo::GripperControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_demo::GripperControlResponse_<ContainerAllocator1> & lhs, const ::move_demo::GripperControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_demo::GripperControlResponse_<ContainerAllocator1> & lhs, const ::move_demo::GripperControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_demo::GripperControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_demo::GripperControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::GripperControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_demo::GripperControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::GripperControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_demo::GripperControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_demo::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::move_demo::GripperControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_demo::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_demo/GripperControlResponse";
  }

  static const char* value(const ::move_demo::GripperControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_demo::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::move_demo::GripperControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_demo::GripperControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_demo::GripperControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_demo::GripperControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_GRIPPERCONTROLRESPONSE_H
