// Generated by gencpp from file move_demo/SetJointAngles.msg
// DO NOT EDIT!


#ifndef MOVE_DEMO_MESSAGE_SETJOINTANGLES_H
#define MOVE_DEMO_MESSAGE_SETJOINTANGLES_H

#include <ros/service_traits.h>


#include <move_demo/SetJointAnglesRequest.h>
#include <move_demo/SetJointAnglesResponse.h>


namespace move_demo
{

struct SetJointAngles
{

typedef SetJointAnglesRequest Request;
typedef SetJointAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointAngles
} // namespace move_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_demo::SetJointAngles > {
  static const char* value()
  {
    return "8b430f70f7ff32529e5429ef4104cf78";
  }

  static const char* value(const ::move_demo::SetJointAngles&) { return value(); }
};

template<>
struct DataType< ::move_demo::SetJointAngles > {
  static const char* value()
  {
    return "move_demo/SetJointAngles";
  }

  static const char* value(const ::move_demo::SetJointAngles&) { return value(); }
};


// service_traits::MD5Sum< ::move_demo::SetJointAnglesRequest> should match
// service_traits::MD5Sum< ::move_demo::SetJointAngles >
template<>
struct MD5Sum< ::move_demo::SetJointAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_demo::SetJointAngles >::value();
  }
  static const char* value(const ::move_demo::SetJointAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_demo::SetJointAnglesRequest> should match
// service_traits::DataType< ::move_demo::SetJointAngles >
template<>
struct DataType< ::move_demo::SetJointAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::move_demo::SetJointAngles >::value();
  }
  static const char* value(const ::move_demo::SetJointAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_demo::SetJointAnglesResponse> should match
// service_traits::MD5Sum< ::move_demo::SetJointAngles >
template<>
struct MD5Sum< ::move_demo::SetJointAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_demo::SetJointAngles >::value();
  }
  static const char* value(const ::move_demo::SetJointAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_demo::SetJointAnglesResponse> should match
// service_traits::DataType< ::move_demo::SetJointAngles >
template<>
struct DataType< ::move_demo::SetJointAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::move_demo::SetJointAngles >::value();
  }
  static const char* value(const ::move_demo::SetJointAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_DEMO_MESSAGE_SETJOINTANGLES_H
