(cl:defpackage move_demo-srv
  (:use )
  (:export
   "GRIPPERCONTROL"
   "<GRIPPERCONTROL-REQUEST>"
   "GRIPPERCONTROL-REQUEST"
   "<GRIPPERCONTROL-RESPONSE>"
   "GRIPPERCONTROL-RESPONSE"
   "SETJOINTANGLES"
   "<SETJOINTANGLES-REQUEST>"
   "SETJOINTANGLES-REQUEST"
   "<SETJOINTANGLES-RESPONSE>"
   "SETJOINTANGLES-RESPONSE"
  ))

